export const AVAILABLE_SUBJECTS = [
  {
    key: "readingStats",
    label: "Reading",
    emoji: "📖",
    color: "bg-blue-50",
    accentColor: "bg-blue-500",
    textColor: "text-blue-700",
    nav: "ReadingSubject",
  },
  {
    key: "mathStats",
    label: "Math",
    emoji: "🔢",
    color: "bg-purple-50",
    accentColor: "bg-purple-500",
    textColor: "text-purple-700",
    nav: "MathSubject",
  },
  {
    key: "scienceStats",
    label: "Science",
    emoji: "🧪",
    color: "bg-green-50",
    accentColor: "bg-green-500",
    textColor: "text-green-700",
    nav: "ScienceSubject",
  },
  {
    key: "writingStats",
    label: "Writing",
    emoji: "📝",
    color: "bg-orange-50",
    accentColor: "bg-orange-500",
    textColor: "text-orange-700",
    nav: "WritingSubject",
  },
  {
    key: "vocabularyStats",
    label: "Vocabulary",
    emoji: "💭",
    color: "bg-pink-50",
    accentColor: "bg-pink-500",
    textColor: "text-pink-700",
    nav: "VocabularySubject",
  },
];
