import {
  VocabularyExercise,
  VocabularyLanguage,
  VocabularyWord,
} from "../types/vocabulary";

export const exerciseTypes: VocabularyExercise[] = [
  {
    type: "flashcards",
    title: "Flashcards",
    description: "Learn new words with interactive flashcards",
    color: ["#ff7eb3", "#ff758c"],
    icon: "layers-outline",
  },
  {
    type: "quiz",
    title: "Multiple Choice Quiz",
    description: "Test your knowledge with multiple choice questions",
    color: ["#a8edea", "#fed6e3"],
    icon: "help-circle-outline",
  },
  {
    type: "matching",
    title: "Word Matching",
    description: "Match words with their correct translations",
    color: ["#ffecd2", "#fcb69f"],
    icon: "git-merge-outline",
  },
];

const englishBeginnerWords: VocabularyWord[] = [
  {
    id: "en_1",
    word: "Apple",
    translation: "Яблоко",
    example: "I eat an apple every day.",
    exampleTranslation: "Я ем яблоко каждый день.",
    difficulty: "beginner",
  },
  {
    id: "en_2",
    word: "Cat",
    translation: "Кот",
    example: "The cat is sleeping.",
    exampleTranslation: "Кот спит.",
    difficulty: "beginner",
  },
  {
    id: "en_3",
    word: "House",
    translation: "Дом",
    example: "My house is big.",
    exampleTranslation: "Мой дом большой.",
    difficulty: "beginner",
  },
  {
    id: "en_4",
    word: "Water",
    translation: "Вода",
    example: "I drink water.",
    exampleTranslation: "Я пью воду.",
    difficulty: "beginner",
  },
  {
    id: "en_5",
    word: "Book",
    translation: "Книга",
    example: "I read a book.",
    exampleTranslation: "Я читаю книгу.",
    difficulty: "beginner",
  },
  {
    id: "en_6",
    word: "Car",
    translation: "Машина",
    example: "The car is red.",
    exampleTranslation: "Машина красная.",
    difficulty: "beginner",
  },
  {
    id: "en_7",
    word: "Dog",
    translation: "Собака",
    example: "The dog is playing.",
    exampleTranslation: "Собака играет.",
    difficulty: "beginner",
  },
  {
    id: "en_8",
    word: "Sun",
    translation: "Солнце",
    example: "The sun is bright.",
    exampleTranslation: "Солнце яркое.",
    difficulty: "beginner",
  },
  {
    id: "en_9",
    word: "Tree",
    translation: "Дерево",
    example: "The tree is tall.",
    exampleTranslation: "Дерево высокое.",
    difficulty: "beginner",
  },
  {
    id: "en_10",
    word: "Food",
    translation: "Еда",
    example: "I like good food.",
    exampleTranslation: "Мне нравится хорошая еда.",
    difficulty: "beginner",
  },
  {
    id: "en_11",
    word: "School",
    translation: "Школа",
    example: "I go to school.",
    exampleTranslation: "Я хожу в школу.",
    difficulty: "beginner",
  },
  {
    id: "en_12",
    word: "Friend",
    translation: "Друг",
    example: "My friend is nice.",
    exampleTranslation: "Мой друг хороший.",
    difficulty: "beginner",
  },
  {
    id: "en_13",
    word: "Family",
    translation: "Семья",
    example: "I love my family.",
    exampleTranslation: "Я люблю свою семью.",
    difficulty: "beginner",
  },
  {
    id: "en_14",
    word: "Mother",
    translation: "Мама",
    example: "My mother is kind.",
    exampleTranslation: "Моя мама добрая.",
    difficulty: "beginner",
  },
  {
    id: "en_15",
    word: "Father",
    translation: "Папа",
    example: "My father works hard.",
    exampleTranslation: "Мой папа много работает.",
    difficulty: "beginner",
  },
  {
    id: "en_16",
    word: "Happy",
    translation: "Счастливый",
    example: "I am happy today.",
    exampleTranslation: "Я счастлив сегодня.",
    difficulty: "beginner",
  },
  {
    id: "en_17",
    word: "Blue",
    translation: "Синий",
    example: "The sky is blue.",
    exampleTranslation: "Небо синее.",
    difficulty: "beginner",
  },
  {
    id: "en_18",
    word: "Green",
    translation: "Зелёный",
    example: "The grass is green.",
    exampleTranslation: "Трава зелёная.",
    difficulty: "beginner",
  },
  {
    id: "en_19",
    word: "Big",
    translation: "Большой",
    example: "The elephant is big.",
    exampleTranslation: "Слон большой.",
    difficulty: "beginner",
  },
  {
    id: "en_20",
    word: "Small",
    translation: "Маленький",
    example: "The mouse is small.",
    exampleTranslation: "Мышь маленькая.",
    difficulty: "beginner",
  },
];

const englishIntermediateWords: VocabularyWord[] = [
  {
    id: "en_21",
    word: "Beautiful",
    translation: "Красивый",
    example: "The garden is beautiful.",
    exampleTranslation: "Сад красивый.",
    difficulty: "intermediate",
  },
  {
    id: "en_22",
    word: "Important",
    translation: "Важный",
    example: "Education is important.",
    exampleTranslation: "Образование важно.",
    difficulty: "intermediate",
  },
  {
    id: "en_23",
    word: "Interesting",
    translation: "Интересный",
    example: "The movie was interesting.",
    exampleTranslation: "Фильм был интересный.",
    difficulty: "intermediate",
  },
  {
    id: "en_24",
    word: "Difficult",
    translation: "Трудный",
    example: "The test was difficult.",
    exampleTranslation: "Тест был трудный.",
    difficulty: "intermediate",
  },
  {
    id: "en_25",
    word: "Adventure",
    translation: "Приключение",
    example: "We had a great adventure.",
    exampleTranslation: "У нас было отличное приключение.",
    difficulty: "intermediate",
  },
  {
    id: "en_26",
    word: "Knowledge",
    translation: "Знание",
    example: "Knowledge is power.",
    exampleTranslation: "Знание - сила.",
    difficulty: "intermediate",
  },
  {
    id: "en_27",
    word: "Experience",
    translation: "Опыт",
    example: "Experience teaches us.",
    exampleTranslation: "Опыт учит нас.",
    difficulty: "intermediate",
  },
  {
    id: "en_28",
    word: "Creative",
    translation: "Творческий",
    example: "She is very creative.",
    exampleTranslation: "Она очень творческая.",
    difficulty: "intermediate",
  },
  {
    id: "en_29",
    word: "Environment",
    translation: "Окружающая среда",
    example: "We must protect the environment.",
    exampleTranslation: "Мы должны защищать окружающую среду.",
    difficulty: "intermediate",
  },
  {
    id: "en_30",
    word: "Technology",
    translation: "Технология",
    example: "Technology helps us learn.",
    exampleTranslation: "Технологии помогают нам учиться.",
    difficulty: "intermediate",
  },
  {
    id: "en_31",
    word: "Communication",
    translation: "Общение",
    example: "Good communication is essential.",
    exampleTranslation: "Хорошее общение важно.",
    difficulty: "intermediate",
  },
  {
    id: "en_32",
    word: "Opportunity",
    translation: "Возможность",
    example: "This is a great opportunity.",
    exampleTranslation: "Это отличная возможность.",
    difficulty: "intermediate",
  },
  {
    id: "en_33",
    word: "Challenge",
    translation: "Вызов",
    example: "I accept this challenge.",
    exampleTranslation: "Я принимаю этот вызов.",
    difficulty: "intermediate",
  },
  {
    id: "en_34",
    word: "Success",
    translation: "Успех",
    example: "Hard work leads to success.",
    exampleTranslation: "Упорный труд ведёт к успеху.",
    difficulty: "intermediate",
  },
  {
    id: "en_35",
    word: "Confidence",
    translation: "Уверенность",
    example: "She speaks with confidence.",
    exampleTranslation: "Она говорит с уверенностью.",
    difficulty: "intermediate",
  },
  {
    id: "en_36",
    word: "Responsible",
    translation: "Ответственный",
    example: "He is a responsible student.",
    exampleTranslation: "Он ответственный студент.",
    difficulty: "intermediate",
  },
  {
    id: "en_37",
    word: "Independent",
    translation: "Независимый",
    example: "She is very independent.",
    exampleTranslation: "Она очень независимая.",
    difficulty: "intermediate",
  },
  {
    id: "en_38",
    word: "Fantastic",
    translation: "Фантастический",
    example: "The view was fantastic.",
    exampleTranslation: "Вид был фантастический.",
    difficulty: "intermediate",
  },
  {
    id: "en_39",
    word: "Amazing",
    translation: "Удивительный",
    example: "The show was amazing.",
    exampleTranslation: "Шоу было удивительным.",
    difficulty: "intermediate",
  },
  {
    id: "en_40",
    word: "Wonderful",
    translation: "Замечательный",
    example: "We had a wonderful time.",
    exampleTranslation: "Мы замечательно провели время.",
    difficulty: "intermediate",
  },
];

// Russian Words Data
const russianBeginnerWords: VocabularyWord[] = [
  {
    id: "ru_1",
    word: "Привет",
    translation: "Hello",
    example: "Привет, как дела?",
    exampleTranslation: "Hello, how are you?",
    difficulty: "beginner",
  },
  {
    id: "ru_2",
    word: "Спасибо",
    translation: "Thank you",
    example: "Спасибо за помощь.",
    exampleTranslation: "Thank you for help.",
    difficulty: "beginner",
  },
  {
    id: "ru_3",
    word: "Дом",
    translation: "House",
    example: "Мой дом красивый.",
    exampleTranslation: "My house is beautiful.",
    difficulty: "beginner",
  },
  {
    id: "ru_4",
    word: "Мама",
    translation: "Mom",
    example: "Моя мама добрая.",
    exampleTranslation: "My mom is kind.",
    difficulty: "beginner",
  },
  {
    id: "ru_5",
    word: "Папа",
    translation: "Dad",
    example: "Мой папа сильный.",
    exampleTranslation: "My dad is strong.",
    difficulty: "beginner",
  },
  {
    id: "ru_6",
    word: "Кот",
    translation: "Cat",
    example: "Кот спит на диване.",
    exampleTranslation: "The cat sleeps on the sofa.",
    difficulty: "beginner",
  },
  {
    id: "ru_7",
    word: "Собака",
    translation: "Dog",
    example: "Собака лает громко.",
    exampleTranslation: "The dog barks loudly.",
    difficulty: "beginner",
  },
  {
    id: "ru_8",
    word: "Хлеб",
    translation: "Bread",
    example: "Я ем хлеб с маслом.",
    exampleTranslation: "I eat bread with butter.",
    difficulty: "beginner",
  },
  {
    id: "ru_9",
    word: "Молоко",
    translation: "Milk",
    example: "Молоко полезно для здоровья.",
    exampleTranslation: "Milk is good for health.",
    difficulty: "beginner",
  },
  {
    id: "ru_10",
    word: "День",
    translation: "Day",
    example: "Сегодня хороший день.",
    exampleTranslation: "Today is a good day.",
    difficulty: "beginner",
  },
  {
    id: "ru_11",
    word: "Ночь",
    translation: "Night",
    example: "Ночь была тёмная.",
    exampleTranslation: "The night was dark.",
    difficulty: "beginner",
  },
  {
    id: "ru_12",
    word: "Солнце",
    translation: "Sun",
    example: "Солнце светит ярко.",
    exampleTranslation: "The sun shines brightly.",
    difficulty: "beginner",
  },
  {
    id: "ru_13",
    word: "Луна",
    translation: "Moon",
    example: "Луна красивая сегодня.",
    exampleTranslation: "The moon is beautiful today.",
    difficulty: "beginner",
  },
  {
    id: "ru_14",
    word: "Школа",
    translation: "School",
    example: "Я хожу в школу каждый день.",
    exampleTranslation: "I go to school every day.",
    difficulty: "beginner",
  },
  {
    id: "ru_15",
    word: "Книга",
    translation: "Book",
    example: "Эта книга очень интересная.",
    exampleTranslation: "This book is very interesting.",
    difficulty: "beginner",
  },
  {
    id: "ru_16",
    word: "Друг",
    translation: "Friend",
    example: "Мой друг очень хороший.",
    exampleTranslation: "My friend is very good.",
    difficulty: "beginner",
  },
  {
    id: "ru_17",
    word: "Игра",
    translation: "Game",
    example: "Мы играем в интересную игру.",
    exampleTranslation: "We play an interesting game.",
    difficulty: "beginner",
  },
  {
    id: "ru_18",
    word: "Музыка",
    translation: "Music",
    example: "Я люблю слушать музыку.",
    exampleTranslation: "I love listening to music.",
    difficulty: "beginner",
  },
  {
    id: "ru_19",
    word: "Красивый",
    translation: "Beautiful",
    example: "Цветок очень красивый.",
    exampleTranslation: "The flower is very beautiful.",
    difficulty: "beginner",
  },
  {
    id: "ru_20",
    word: "Большой",
    translation: "Big",
    example: "Слон очень большой.",
    exampleTranslation: "The elephant is very big.",
    difficulty: "beginner",
  },
];

//constant/Vocabulary.tsx
const russianIntermediateWords: VocabularyWord[] = [
  {
    id: "ru_21",
    word: "Образование",
    translation: "Education",
    example: "Образование очень важно.",
    exampleTranslation: "Education is very important.",
    difficulty: "intermediate",
  },
  {
    id: "ru_22",
    word: "Путешествие",
    translation: "Travel",
    example: "Путешествие было увлекательным.",
    exampleTranslation: "The travel was fascinating.",
    difficulty: "intermediate",
  },
  {
    id: "ru_23",
    word: "Культура",
    translation: "Culture",
    example: "Русская культура богатая.",
    exampleTranslation: "Russian culture is rich.",
    difficulty: "intermediate",
  },
  {
    id: "ru_24",
    word: "Искусство",
    translation: "Art",
    example: "Искусство вдохновляет людей.",
    exampleTranslation: "Art inspires people.",
    difficulty: "intermediate",
  },
  {
    id: "ru_25",
    word: "Традиция",
    translation: "Tradition",
    example: "Эта традиция очень старая.",
    exampleTranslation: "This tradition is very old.",
    difficulty: "intermediate",
  },
  {
    id: "ru_26",
    word: "Развитие",
    translation: "Development",
    example: "Развитие науки важно.",
    exampleTranslation: "Development of science is important.",
    difficulty: "intermediate",
  },
  {
    id: "ru_27",
    word: "Достижение",
    translation: "Achievement",
    example: "Это большое достижение.",
    exampleTranslation: "This is a great achievement.",
    difficulty: "intermediate",
  },
  {
    id: "ru_28",
    word: "Творчество",
    translation: "Creativity",
    example: "Творчество развивает ум.",
    exampleTranslation: "Creativity develops the mind.",
    difficulty: "intermediate",
  },
  {
    id: "ru_29",
    word: "Вдохновение",
    translation: "Inspiration",
    example: "Природа даёт вдохновение.",
    exampleTranslation: "Nature gives inspiration.",
    difficulty: "intermediate",
  },
  {
    id: "ru_30",
    word: "Удивительный",
    translation: "Amazing",
    example: "Это удивительное открытие.",
    exampleTranslation: "This is an amazing discovery.",
    difficulty: "intermediate",
  },
  {
    id: "ru_31",
    word: "Замечательный",
    translation: "Wonderful",
    example: "У нас замечательная погода.",
    exampleTranslation: "We have wonderful weather.",
    difficulty: "intermediate",
  },
  {
    id: "ru_32",
    word: "Превосходный",
    translation: "Excellent",
    example: "Это превосходная работа.",
    exampleTranslation: "This is excellent work.",
    difficulty: "intermediate",
  },
  {
    id: "ru_33",
    word: "Ответственность",
    translation: "Responsibility",
    example: "Ответственность важна в работе.",
    exampleTranslation: "Responsibility is important in work.",
    difficulty: "intermediate",
  },
  {
    id: "ru_34",
    word: "Независимость",
    translation: "Independence",
    example: "Независимость даёт свободу.",
    exampleTranslation: "Independence gives freedom.",
    difficulty: "intermediate",
  },
  {
    id: "ru_35",
    word: "Возможность",
    translation: "Opportunity",
    example: "Это хорошая возможность.",
    exampleTranslation: "This is a good opportunity.",
    difficulty: "intermediate",
  },
  {
    id: "ru_36",
    word: "Необходимость",
    translation: "Necessity",
    example: "Учёба - это необходимость.",
    exampleTranslation: "Study is a necessity.",
    difficulty: "intermediate",
  },
  {
    id: "ru_37",
    word: "Приключение",
    translation: "Adventure",
    example: "Нас ждёт интересное приключение.",
    exampleTranslation: "An interesting adventure awaits us.",
    difficulty: "intermediate",
  },
  {
    id: "ru_38",
    word: "Исследование",
    translation: "Research",
    example: "Исследование длилось год.",
    exampleTranslation: "The research lasted a year.",
    difficulty: "intermediate",
  },
  {
    id: "ru_39",
    word: "Сотрудничество",
    translation: "Cooperation",
    example: "Сотрудничество помогает достичь цели.",
    exampleTranslation: "Cooperation helps achieve goals.",
    difficulty: "intermediate",
  },
  {
    id: "ru_40",
    word: "Понимание",
    translation: "Understanding",
    example: "Понимание приходит с опытом.",
    exampleTranslation: "Understanding comes with experience.",
    difficulty: "intermediate",
  },
];

// Language Configuration
export const VOCABULARY_LANGUAGES: VocabularyLanguage[] = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇺🇸",
    levels: [
      {
        id: "en_beginner",
        name: "Beginner",
        emoji: "🌱",
        description: "Basic everyday words",
        difficulty: "beginner",
        words: englishBeginnerWords,
      },
      {
        id: "en_intermediate",
        name: "Intermediate",
        emoji: "🌳",
        description: "Common phrases and concepts",
        difficulty: "intermediate",
        words: englishIntermediateWords,
      },
    ],
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    levels: [
      {
        id: "ru_beginner",
        name: "Beginner",
        emoji: "🌱",
        description: "Basic everyday words",
        difficulty: "beginner",
        words: russianBeginnerWords,
      },
      {
        id: "ru_intermediate",
        name: "Intermediate",
        emoji: "🌳",
        description: "Common phrases and concepts",
        difficulty: "intermediate",
        words: russianIntermediateWords,
      },
    ],
  },
];
